### PR TITLE
Kraken gb

### PR DESCRIPTION
**Pull request by goodboy**
@iamzoltan you obviously need to rebase your branch to `piker:master` for the massive change set to not show 😂

Added a new order msg stream processor to get you started on translation for the ems relay dialog.

Cheers!

### CODE REVIEW

**Comment by goodboy** [comment]
Last call before I close this and push forward on https://github.com/pikers/piker/pull/282

**Comment by iamzoltan** [comment]
fixed conflicts, ready to merge and the pull, any thing I am missing?

**Comment by goodboy** [comment]
Oh weird this looks right?
I wonder why the source branch looks wrong?

Maybe it's just GH?

**Comment by goodboy** [comment]
Wait, [made comment on the PR to your fork](https://github.com/iamzoltan/piker/pull/1#issuecomment-1039475081).

Not sure why GH showing it this way here..

**Pull request merged**
